#!/system/bin/sh
############################################################
# This script is part of sediROM
#
# Copyright (c) 2014-2015 by Thomas Fischer, www.se-di.de
# v2.1
############################################################

echo "sediROM: starting $0" >> /dev/kmsg

############################################################
# enable modifying 
#
mount -oremount,rw /

############################################################
# compat hack when coming from jelly bean back to ICS..
#
mkdir /storage
ln -s /mnt/sdcard /storage/sdcard0
ln -s /mnt/sdcard/external_sd /storage/sdcard1

############################################################
# remount as ro again at the end
#
mount -oremount,ro /

echo "sediROM: $0 finished" >> /dev/kmsg
