#!/system/bin/sh
############################################################
#
# Copyright (c) 2015 by Thomas Fischer, www.se-di.de
# All rights reserved.
# v2.4
#
# This script is part of sediROM.
############################################################

echo "$(date +%D_%T) - sediROM($0): starting. Should be executed by cron." >> /dev/kmsg

# path where the config and log will be saved
SEDIDIR=/preload/.sediROM/

# Indicator file will be added by shutdown script and that requires at least 1 clean shutdown.
IFLAG=$SEDIDIR/.initialized

############################################################
# ensure that /data is not encrypted and if so we wait until it will
# be unlocked by the user
ENCSTATE=$(getprop vold.post_fs_data_done)

# ensure that system has booted completely
BOOTSTATE=$(getprop sys.boot_completed)

while [ ! -f "$IFLAG" ] || [ ! "x$ENCSTATE" == "x1" ] || [ ! "x$BOOTSTATE" == "x1" ];do
    echo "$(date +%D_%T) - sediROM($0): /data (still) locked or sediROM is not fully initialized." >> /dev/kmsg
    RETIFLAG=$(test -f "$IFLAG")
    echo "$(date +%D_%T) - sediROM($0): boot state was: $BOOTSTATE (should be empty or 1)." >> /dev/kmsg
    echo "$(date +%D_%T) - sediROM($0): $IFLAG test was: $RETIFLAG (should be empty or 0)." >> /dev/kmsg
    echo "$(date +%D_%T) - sediROM($0): Encryption test was: $ENCSTATE (should be 1)." >> /dev/kmsg
    sleep 10s
    # re-check states
    ENCSTATE=$(getprop vold.post_fs_data_done)
    BOOTSTATE=$(getprop sys.boot_completed)
    
    # ensure sdcard was initialized
    while [ ! -d "/sdcard/.sediROM" ];do sleep 3s ;done
    
    # if we were not able to use preload as log storage we will use sdcard instead    
    SEDISDDIR=/sdcard/.sediROM # if we cannot mount /preload this is a fallback
    INDIMOVED=$SEDISDDIR/dir-moved-2-preload.txt # indicator file to know if we are using preload or not               
    if [ ! -f "$INDIMOVED" ];then                                                                              
        SEDIDIR=$SEDISDDIR
    fi                                                                                                         
    echo "$(date +%D_%T) - sediROM($0): initflag dir set to $SEDIDIR" >> /dev/kmsg
    IFLAG=$SEDIDIR/.initialized
done

# set working dir according to the above result
WRKDIR=$SEDIDIR/bin
LOG=$WRKDIR/${0##*/}.log

# setup work dir
[ ! -d $WRKDIR ] && mkdir -p $WRKDIR

echo "$(date) sediROM: starting $0" > $LOG

############################################################
# Fix crappy Google Play Framework causing battery drain
# Details:
# http://forum.xda-developers.com/showpost.php?p=53881089
# http://muzso.hu/2014/09/18/how-to-fix-the-partial-wakelock-problem-on-cyanogenmod-11-with-google-play-services-and-o
#
# Additionally to the above orig post you HAVE TO(!) to escape the $ sign!
#
pm disable com.google.android.gms/.update.SystemUpdateService\$SecretCodeReceiver >> $LOG 2>&1                            
pm disable com.google.android.gms/.update.SystemUpdateActivity >> $LOG 2>&1                                               
pm disable com.google.android.gms/.update.SystemUpdateService >> $LOG 2>&1                                               
pm disable com.google.android.gms/.update.SystemUpdateService\$ActiveReceiver >> $LOG 2>&1                               
pm disable com.google.android.gms/.update.SystemUpdateService\$Receiver >> $LOG 2>&1                                   
pm disable com.google.android.gms/.update.SystemUpdateService\$SecretCode >> $LOG 2>&1                                  
pm disable com.google.android.gsf/.update.SystemUpdateActivity >> $LOG 2>&1                                      
pm disable com.google.android.gsf/.update.SystemUpdatePanoActivity >> $LOG 2>&1                                        
pm disable com.google.android.gsf/.update.SystemUpdateService >> $LOG 2>&1                                         
pm disable com.google.android.gsf/.update.SystemUpdateService\$Receiver >> $LOG  2>&1                                     
pm disable com.google.android.gsf/.update.SystemUpdateService\$SecretCode >> $LOG  2>&1                                   
echo "$(date): Disabling Google Play bullshit ended with errorcode: $?"  >> $LOG 

echo "$(date +%D_%T) - sediROM($0): finished. waiting for the next cron run." >> /dev/kmsg
    
####################################################################
######## NO CODE BEHIND THIS LINE ##################################
####################################################################