#!/system/bin/sh
############################################################
# This script is part of sediROM
# Copyright (c) 2014 by Thomas Fischer, www.se-di.de
# v0.5
############################################################


############################################################
# enable modifying 
#
mount -oremount,rw /

############################################################
# compat hack when coming from jelly bean back to ICS..
#
mkdir /storage
ln -s /mnt/sdcard /storage/sdcard0
ln -s /mnt/sdcard/external_sd /storage/sdcard1

#############################################################
# bluetooth loosing paired devices workaround
# (see also K99sediROM_btfix for the first part)
#
WRKDIR=/data/local/tmp
BTNAME=00_btbackup.tar
BTBAK=$WRKDIR/$BTNAME
LOG=$WRKDIR/${BTNAME}.log

echo "$(date +%D_%T): Starting BT fix part2 (onboot execution).."  >> $LOG

if [ -f $BTBAK ];then
    chattr -i /data/misc/bluetoothd/*/config \
    && tar -C / -xvf $BTBAK 2>&1 >> $LOG \
    && chown bluetooth /data/misc/bluetoothd 2>&1 >> $LOG \
    && chgrp -Rv bluetooth /data/misc/bluetoothd 2>&1 >> $LOG \
    && chown system /data/misc/bluetooth 2>&1 >> $LOG \
    && chgrp -Rv system /data/misc/bluetooth 2>&1 >> $LOG \
    && echo "$(date +%D_%T): All restoring done sucessfully!" >> $LOG
else
    echo "$(date +%D_%T): No previous backup detected. Skipping restore.."
fi

############################################################
# remount as ro again at the end
#
mount -oremount,ro /
