#!/system/bin/sh
#########################################################################
#
# Copyright (c) 2014-2015 by Thomas Fischer, www.se-di.de
# All rights reserved.
#
# This script is part of sediROM.
#########################################################################

echo "$(date +%D_%T) - sediROM($0): starting" >> /dev/kmsg

# path where the config and log will be saved. the initialization is made by sediROM shutdown script.
# Thats one of the reasons why we need to reboot at least once in order to get fully working system.
SEDIDIR=/preload/.sediROM

# Indicator file will be added by shutdown script and that requires at least 1 clean shutdown.
IFLAG=$SEDIDIR/.initialized

############################################################
# ensure that /data is not encrypted and if so we wait until it will
# be unlocked by the user
ENCSTATE=$(getprop vold.post_fs_data_done)

# ensure that system has booted completely
BOOTSTATE=$(getprop sys.boot_completed)

while [ ! -f "$IFLAG" ] || [ ! "x$ENCSTATE" == "x1" ]|| [ ! "x$BOOTSTATE" == "x1" ];do
    ENCSTATE=$(getprop vold.post_fs_data_done)
    echo "$(date +%D_%T) - sediROM($0): /data (still) locked or sediROM is not fully initialized." >> /dev/kmsg
    RETIFLAG=$(test -f "$IFLAG")
    echo "$(date +%D_%T) - sediROM($0): boot state was: $BOOTSTATE (should be empty or 1)." >> /dev/kmsg
    echo "$(date +%D_%T) - sediROM($0): $IFLAG test was: >$RETIFLAG< (should be empty or 0)." >> /dev/kmsg
    echo "$(date +%D_%T) - sediROM($0): Encryption test was: $ENCSTATE (should be 1)." >> /dev/kmsg
    sleep 3s
    # re-check states
    ENCSTATE=$(getprop vold.post_fs_data_done)
    BOOTSTATE=$(getprop sys.boot_completed)
    
    # ensure sdcard was initialized
    while [ ! -d "/sdcard/.sediROM" ];do sleep 3s ;done
    
    # if we were not able to use preload as log storage we will use sdcard instead    
    SEDISDDIR=/sdcard/.sediROM # if we cannot mount /preload this is a fallback
    INDIMOVED=$SEDISDDIR/dir-moved-2-preload.txt # indicator file to know if we are using preload or not               
    if [ ! -f "$INDIMOVED" ];then                                                                              
        SEDIDIR=$SEDISDDIR
    fi                                                                                                         
    echo "$(date +%D_%T) - sediROM($0): initflag dir set to $SEDIDIR" >> /dev/kmsg
    IFLAG=$SEDIDIR/.initialized
done
echo "$(date +%D_%T) - sediROM($0): starting $0" >> /dev/kmsg

# set working dir according to the above result
WRKDIR=$SEDIDIR/initd
LOG=$WRKDIR/${0##*/}.log

echo "$(date) sediROM: starting" > $LOG

# setup work dir
[ ! -d $WRKDIR ] && mkdir -p $WRKDIR

# ==============================================================
# Optimize SQlite databases
# ==============================================================

#echo "";
#echo "*********************************************";
#echo "Optimizing and defragging your database files (*.db)";
#echo "Ignore the 'database disk image is malformed' error";
#echo "Ignore the 'no such collation sequence' error";
#echo "*********************************************";
#echo "";

for i in \
`busybox find /data -iname "*.db"`; 
do \
    echo "processing $i ..." >> $LOG
	/system/xbin/sqlite3 $i 'VACUUM;'; >> $LOG
	/system/xbin/sqlite3 $i 'REINDEX;'; >> $LOG
done;

for i in \
`busybox find /sdcard -iname "*.db"`; 
do \
    echo "processing $i ..." >> $LOG
	/system/xbin/sqlite3 $i 'VACUUM;'; >> $LOG
	/system/xbin/sqlite3 $i 'REINDEX;'; >> $LOG
done;

echo "$(date) sediROM: finished" >> $LOG
echo "$(date +%D_%T) - sediROM($0): finished" >> /dev/kmsg
